添加22级2023春夏wzx班线代2
ZJU-Turing/TuringCourses pull request #135
Opened 2024-02-06 15:34 UTC by kuaikuaixym

2024-02-06 16:27 UTC, TonyCrane approved these changes
修了一下，有一些问题可以以后注意一下：

- 有一些右括号漏了（？），至少这里还是尽量配对
- markdown 里单纯换行是两段文字连接的效果而不是换行，详见 https://hypotensor.tonycrane.cc/ta/markdown/syntax/#_1
- 老师评价这里混入了一点学习建议，感觉在这里不太合适而且删掉了其实问题也不大（？）

2024-02-06 16:29 UTC, TonyCrane commented
（其他人如果要直接 merge 的话记得在 message content 里把我的 co-author 删掉）

2024-02-07 04:09 UTC, 45gfg9 approved these changes

2024-02-07 04:22 UTC, shadowash0215 requested changes
麻烦把正文和文件名中对应的人名缩写修改一下

2024-02-07 04:57 UTC, kuaikuaixym commented
已修改

2024-02-07 10:14 UTC, shadowash0215 approved these changes

2024-02-07 10:19 UTC, merged