Update index.md of military_theory
ZJU-Turing/TuringCourses pull request #143
Opened 2024-02-12 15:07 UTC by dieKarotte

include overall introduction to the course and comments for some teachers.

2024-02-12 15:55 UTC, TonyCrane requested changes
其他地方，神

2024-02-12 15:55 UTC, TonyCrane commented on docs/political/military_theory/index.md
> +    - 历年题打印出来带入考场，碰到重复的题目会很快解决，节省时间
这是什么格式……不空行+列表缩进……鲨

<img width="786" alt="image" src="https://github.com/ZJU-Turing/TuringCourses/assets/44120331/74da9341-25f0-443d-a3c4-9c4f486946b6">

2024-02-12 15:55 UTC, TonyCrane commented on docs/political/military_theory/index.md
> +        - 签到、回答问题等 10%
为什么要缩进呢，不理解，缩进是代码块啊

<img width="380" alt="image" src="https://github.com/ZJU-Turing/TuringCourses/assets/44120331/6fd7d798-0368-4432-ab1b-7407702a514c">

2024-02-12 15:56 UTC, TonyCrane approved these changes
改好了

2024-02-13 03:34 UTC, dieKarotte commented
我的问题，没本地预览

2024-02-13 04:49 UTC, merged