docs: 添加电子工程训练（甲）课程内容和劳育认定标识
ZJU-Turing/TuringCourses pull request #147
Opened 2024-02-16 07:48 UTC by Zhroyn

2024-02-16 12:03 UTC, TonyCrane approved these changes

2024-02-16 14:44 UTC, shadowash0215 approved these changes

2024-02-16 16:37 UTC, TonyCrane requested changes
把页面名称改成电子工程训练，然后一个页面里面两个二级标题区分甲和乙（原来页面里的标题都降低一级，类似 wyy 的经济和金融）

这个 PR 改完 merge 了之后 @yegroup001 把 #149 的东西加到同一页面里（可以等着直接 sync 分支再改不用删掉原来的 PR），记得 index 的表格里面还是按两个课程写。

2024-02-17 05:14 UTC, TonyCrane approved these changes

2024-02-17 05:18 UTC, merged