docs: 更新普通物理学实验Ⅱ 课程内容
ZJU-Turing/TuringCourses pull request #164
Opened 2024-02-25 14:20 UTC by Frankoxer

2024-02-25 15:42 UTC, TonyCrane requested changes
在数理基础的 index 页把普物实验二改成较完善吧

2024-02-25 23:57 UTC, Frankoxer commented
已修改

2024-02-26 02:08 UTC, Frankoxer commented
> 已修改

comments 写错了qaq 是普物实验 Ⅱ

2024-02-26 04:30 UTC, TonyCrane approved these changes

2024-02-26 04:31 UTC, merged