docs: 添加毛概、量子计算理论基础与软件系统课程内容，更新应用运筹学基础课程内容
ZJU-Turing/TuringCourses pull request #174
Opened 2024-03-11 03:31 UTC by HobbitQia

2024-03-11 12:21 UTC, ZhouTimeMachine approved these changes

2024-03-11 16:52 UTC, TonyCrane requested changes
语法混乱小子/尊嘟假嘟

2024-03-11 16:52 UTC, TonyCrane commented on docs/major_elective/quantum_computing/index.md
> +实验课不要求线下到场，助教会以群直播的方式同步在钉钉群里，主要介绍实验平台，作业和实验的一些要求。
助教会 以群直播的方式 同步 在钉钉群里

什么语法这是

2024-03-11 16:52 UTC, TonyCrane commented on docs/major_elective/quantum_computing/index.md
> +实验课不要求线下到场，助教会以群直播的方式同步在钉钉群里，主要介绍实验平台，作业和实验的一些要求。
平台、作业和实验

什么标点这是

2024-03-11 16:52 UTC, TonyCrane commented on docs/major_elective/quantum_computing/index.md
> +本课程是 23-24 秋冬学期开课，老师可能高估了大家的线代水平，因此课程进度和预期安排有较大出入。实际上前半学期都在讲线性代数和量子算法，后面主要讲了量子计算的应用。不排除后面可能会修改教学大纲的可能。
可能 会修改教学大纲 的可能

什么语法这是

2024-03-11 16:52 UTC, TonyCrane commented on docs/major_elective/quantum_computing/index.md
> +    卢老师本人是做量子方向，水平非常高，老师人也很好，会根据大家的听课情况调整进度。对于线性代数部分大家不太清楚的地方直接在黑板上一步一步推导。给分也比较慷慨，据老师自己说会尽量往高的给。老师有时也会问大家有没有兴趣去实验室旁听组会。此外老师可能还会请一些大咖来做讲座，比如 23-24 秋冬学期请到了 [周经森老师](https://person.zju.edu.cn/kingsum) 来给
中文句子中间不要出现空格……

2024-03-11 16:52 UTC, TonyCrane commented on docs/major_elective/quantum_computing/index.md
> +虽然看大纲这门课的内容很多，但实际上许多内容都并没有过多的深入，只是简单介绍。重点其实还是在前面的线性代数和量子算法上。不排除以后可能会上强度的可能（逃）。
又是 可能……的可能

2024-03-11 16:52 UTC, TonyCrane commented on docs/major_module/applied_operations_research/index.md
> +    * 3 人一组，从 30+ 篇论文中选择 1 篇，按照助教安排的时间表进行 pre 。20 级论文大概分为 steiner 树和次模优化两个主题；21 级的论文的主题有 AI4OR、Network Interdiction、Santa Claus、Fair Division。有的论文非常有难度，甚至会有当年 STOC/FOCS（理论计算机顶会）的 best paper。
前面空格修了这里空格不修是吧

2024-03-11 16:52 UTC, TonyCrane commented on docs/major_module/applied_operations_research/index.md
> +    * 张国川的期望是小班教学并进行面试，但是 20 级时 50+ 的学生太多了无法面试，委婉地使用了 “练习” 作为期末考试的代称。尽管张国川称呼期末测试为 “练习” ，但是下手并不会手软，难度相当高，没有机械使用计算方法的题，几乎全部是证明题。另外完成度非常重要，一定的完成度下，一道小题的差距可能是两档甚至三档的分数差距。
中文引号左右不加空格，也修一下

2024-03-11 16:52 UTC, TonyCrane commented on docs/political/mao_thought/index.md
> +            * 随堂小测（会提前通知），占比 10%。
句号都可以删掉

2024-03-12 02:47 UTC, TonyCrane approved these changes

2024-03-12 02:48 UTC, merged