ads, oop, toc changed by zjj
ZJU-Turing/TuringCourses pull request #38
Opened 2023-02-26 08:36 UTC by ZhouTimeMachine

ads: add description of Wang Can, and note of zjj
oop: add note of zjj
toc: write totally

2023-02-26 08:59 UTC, TonyCrane requested changes
toc 的我回去再调一下

2023-02-26 08:59 UTC, TonyCrane commented on docs/major_basic/advanced_data_structure/index.md
> +    3. 纵观 ads 各教学班教学风格，大致可分为 “原理派” 和 “实现派”，其中陈越、何钦铭是 “实现派” 的代表，从陈越的 ppt 就可以看出，侧重代码逻辑，原理并没有非常清楚深入；而张国川、叶德仕、毛宇尘是 “原理派” 的代表，他们几乎不讲代码实现，但是会把原理讲得非常深入，甚至会拓展。而王灿的优势在于他可以分入 “实现派” 阵营（使用陈越 ppt ），但是在很多地方会给出额外的很
这部分概述的感觉可以提到外面（所有老师前面）

2023-02-26 10:07 UTC, TonyCrane approved these changes

2023-02-26 10:08 UTC, merged

2023-02-27 03:23 UTC, Guahao31 commented
ToC 引用 jxg 这里有个错别字 

line 84

>  “我本来呢，是给大家列一个列表的，但我后来发现大家不过是网上随便抄抄的东西。那我个人觉得，就是这个最后的***十***分，我需要你们来真正地思考。什么是真正的计算机科学？所以就这个计算科学相关的问题来做思考。那么我就不做列表，因为我觉得那个列表不好，最后后来很多人把自己实验室里胡乱学的一篇文章（拿来应付这个任务）。我的课不需要，我更需要的是来思考思想。所以我希望最后在考试之前，最后每个人提交一篇可长可短，但是必须是自己思考的东西。你可以长可以短，那我觉得你短了之后，你能解决问题就可以，是吧？” —— jxg, 2022.9.12