docs: 添加优化基本理论与方法内容
ZJU-Turing/TuringCourses pull request #45
Opened 2023-03-01 13:37 UTC by ZhouTimeMachine

2023-03-01 14:58 UTC, TonyCrane requested changes

2023-03-01 14:58 UTC, TonyCrane commented on docs/major_basic/convex_optimization/index.md
> +    包括 4 次普通作业和 1 次 mid-term ，普通作业一次布置 3-6 道题目，大部分都能够在 PPT 或者书上找到答案。 Mid-term 则要求写代码、测试、写报告， 20 级的题目是用普通梯度下降法、拟牛顿法和共轭梯度法在小数据集上实现岭回归。注意作业和报告都是用 latex 写的，会发 latex 的模板，只要配好环境通过编译一关，修改对应的空处就可以快乐完成作业了。如果仔
卷子哥现在开始多加空格了（x

英文接中文标点是不用加空格的，因为英文单词接英文标点也是没空格的（

后面好像还有好多

2023-03-01 14:58 UTC, TonyCrane commented on docs/major_basic/convex_optimization/index.md
> +    包括 4 次普通作业和 1 次 mid-term ，普通作业一次布置 3-6 道题目，大部分都能够在 PPT 或者书上找到答案。 Mid-term 则要求写代码、测试、写报告， 20 级的题目是用普通梯度下降法、拟牛顿法和共轭梯度法在小数据集上实现岭回归。注意作业和报告都是用 latex 写的，会发 latex 的模板，只要配好环境通过编译一关，修改对应的空处就可以快乐完成作业了。如果仔
以及这里建议把 LaTeX 大小写打出来

2023-03-01 17:12 UTC, floatshadow commented on docs/major_basic/convex_optimization/index.md
> +    包括 4 次普通作业和 1 次 mid-term ，普通作业一次布置 3-6 道题目，大部分都能够在 PPT 或者书上找到答案。 Mid-term 则要求写代码、测试、写报告， 20 级的题目是用普通梯度下降法、拟牛顿法和共轭梯度法在小数据集上实现岭回归。注意作业和报告都是用 latex 写的，会发 latex 的模板，只要配好环境通过编译一关，修改对应的空处就可以快乐完成作业了。如果仔
建议同学们懒得配环境可以用 Overleaf

2023-03-02 06:56 UTC, TonyCrane requested changes

2023-03-02 06:56 UTC, TonyCrane commented on docs/major_basic/convex_optimization/index.md
> +    包括 4 次普通作业和 1 次 mid-term，普通作业一次布置 3-6 道题目，大部分都能够在 PPT 或者书上找到答案。 Mid-term 则要求写代码、测试、写报告， 20 级的题目是用普通梯度下降法、拟牛顿法和共轭梯度法在小数据集上实现岭回归。注意作业和报告都是用 LaTex 写的，会发 LaTex 的模板，只要配好环境通过编译一关，修改对应的空处就可以快乐完成作业了。如果仔细
LaTeX 的 X 大写喵

overleaf 可以加上个链接

2023-03-02 06:56 UTC, TonyCrane commented on docs/major_basic/convex_optimization/index.md
> +    同样会给一个 LaTex 报告模板，按照模板要求写就行了。会给几个研究方向，每个方向给一篇参考论文，选择一个研究方向写一篇报告即可。 20 级所给的三个方向是从 ODE/Geometry/Game Theory 的角度研究加速梯度下降。或许写成论文翻译，或许写成文献综述，也有真正的大佬疯狂推公式真的在做研究，看你想要做到什么程度。
这里 / 左右加空格没问题的，我觉得加空格更好看一点

2023-03-02 16:13 UTC, TonyCrane approved these changes

2023-03-02 16:13 UTC, floatshadow approved these changes
LGTM

2023-03-03 10:03 UTC, merged