docs: 添加计算摄影学内容
ZJU-Turing/TuringCourses pull request #63
Opened 2023-07-02 16:29 UTC by ZhouTimeMachine

2023-07-02 16:40 UTC, TonyCrane requested changes
拷打❗️

2023-07-02 16:40 UTC, TonyCrane commented on docs/major_elective/computational_photography/index.md
> +零基础也能学（笑）所有用到的基础都会简单地讲一遍，如果没有先修的话或许也能学会，只是要付出更多的精力。具体而言，这门课会用到（或重复教授）以下三门课的相关知识：
零基础是吧

2023-07-02 16:40 UTC, TonyCrane commented on docs/major_elective/computational_photography/index.md
> +除了深度学习之外的所有小实验，以及大程的部分选题目前都是要求用 C++ 实现的，甚至部分实验会给出代码框架（如接口类）要求具体实现。但是以后会不会改用别的呢？这是一个问题。
问问题草

“但是不保证以后不会改用其他框架” 或者直接删掉

2023-07-02 16:40 UTC, TonyCrane commented on docs/major_elective/computational_photography/index.md
> +无。面向前沿的专业课哪来的教材？读论文去吧。
正经一点啊喂

2023-07-02 16:40 UTC, TonyCrane commented on docs/major_elective/computational_photography/index.md
> +    - 偶尔会有签到，章国锋的课签到概率比较高。签到如何计入成绩暂时未知
。 -> ，

2023-07-02 16:40 UTC, TonyCrane commented on docs/major_elective/computational_photography/index.md
> +    - 20 级只有单刷和 2 人队。每个项目会有 bonus，2 人队必做部分 bonus，单刷做了 bonus 可以加分。
唐突句号

2023-07-02 16:40 UTC, TonyCrane commented on docs/major_elective/computational_photography/index.md
> +## 大程选题
二级标题是不是太大了，感觉可以放到分数构成或者学习内容里面？

2023-07-02 16:40 UTC, TonyCrane commented on docs/major_elective/computational_photography/index.md
> +周晓巍老师是神。人比较温柔，讲课也引人入胜，能够把课程内容从细微之处到最前沿讲得清清楚楚，ai 的同学学过他的 cv 导论应该就非常清楚了。zgf 和 zxw 各讲一半的课，导致笔者一半的课学得很清楚，另一半学得迷迷糊糊。最后的大程，绝大部分同学选的也是 zxw 老师讲解的主题相关的大程（笑）
用 tab 的格式

```markdown
=== "章国锋"
	
	...

=== "周晓巍"

	...
```

2023-07-03 02:12 UTC, ZhouTimeMachine commented on docs/major_elective/computational_photography/index.md
> +零基础也能学（笑）所有用到的基础都会简单地讲一遍，如果没有先修的话或许也能学会，只是要付出更多的精力。具体而言，这门课会用到（或重复教授）以下三门课的相关知识：
强大的零基础学什么都行！

2023-07-03 02:12 UTC, ZhouTimeMachine commented on docs/major_elective/computational_photography/index.md
> +除了深度学习之外的所有小实验，以及大程的部分选题目前都是要求用 C++ 实现的，甚至部分实验会给出代码框架（如接口类）要求具体实现。但是以后会不会改用别的呢？这是一个问题。
正文确实不合适，考虑放在评论区

2023-07-03 02:12 UTC, ZhouTimeMachine commented on docs/major_elective/computational_photography/index.md
> +无。面向前沿的专业课哪来的教材？读论文去吧。
好的好的

2023-07-03 02:13 UTC, ZhouTimeMachine commented on docs/major_elective/computational_photography/index.md
> +## 大程选题
行

2023-07-03 02:13 UTC, ZhouTimeMachine commented on docs/major_elective/computational_photography/index.md
> +周晓巍老师是神。人比较温柔，讲课也引人入胜，能够把课程内容从细微之处到最前沿讲得清清楚楚，ai 的同学学过他的 cv 导论应该就非常清楚了。zgf 和 zxw 各讲一半的课，导致笔者一半的课学得很清楚，另一半学得迷迷糊糊。最后的大程，绝大部分同学选的也是 zxw 老师讲解的主题相关的大程（笑）
由于是两位老师共同开设，所以就不按照这样的格式了

2023-07-03 04:22 UTC, TonyCrane approved these changes

2023-07-03 04:44 UTC, merged