docs: 更新嵌入式、添加体系结构 OS 内容
ZJU-Turing/TuringCourses pull request #82
Opened 2023-07-11 08:52 UTC by zhouyangye1076

2023-07-11 11:32 UTC, TonyCrane requested changes

2023-07-11 11:32 UTC, TonyCrane commented on docs/major_mandatory/computer_architecture/index.md
> +* 乱序的几种策略，如纯stall、scoreboard、register remaining、tomasula、reorder buffer等
是 register renaming、tomasulo 吧

2023-07-11 11:32 UTC, TonyCrane commented on docs/major_mandatory/computer_architecture/index.md
> +</div>
专业必修不分“计算机系统”模块

2023-07-11 11:32 UTC, TonyCrane commented on docs/major_mandatory/computer_architecture/index.md
> +* lab6的bonus给的好像挺多
- 这里要整体缩进
- predict not taken 不是 token
- register renaming
- 括号里面有汉字用全角括号，统一一下就是全都用全角
- 最后一项应该写到 lab6 的下一级

2023-07-11 11:32 UTC, TonyCrane commented on docs/major_mandatory/computer_architecture/index.md
> +其中分支预测的部分只有课上PPT才有。可以买第五版的书，但是现在普遍用riscv指令了，第五版还是mips，PPT没有更新用的也还是MIPS。
- 斜体的星号后面不要加空格，不然这里会解析为列表
- 空一行表示换段落，换行的话要在上一行末尾加两个空格（不过尽量避免）
- 大小写要统一

2023-07-11 11:32 UTC, TonyCrane commented on docs/major_mandatory/computer_architecture/index.md
> +    * lab 6 次(32%)
- 如下后面加冒号
- 少了 40% 期末？

2023-07-11 11:32 UTC, TonyCrane commented on docs/major_mandatory/computer_architecture/index.md
> +体系结构的任务还是比较轻的，课程内容虽然设计的量比较大，包括cache、分支预测、SIMD、多发射、乱序、多核等一系列内容，但是都不是非常深入，大多数重在了解，其中乱序的算法、内存一致性协议达到了定量的程度，其他主要还是定性的程度。lab比计组的简单很多，不同于计组的纯手搓，体系的lab都给了代码，只需要做适当的填空即可，很多时候一个下午就可以了，甚至lab1、lab3、lab4其实计组很多人都
- “lab 虽然也有 -10%” 没看懂什么意思
- 全角点号前后不要加空格

2023-07-11 11:32 UTC, TonyCrane commented on docs/major_module/embedded_system/index.md
> +如果可以选上 wk 老师的课，还是不建议上 wzh 的课的，课上学不到东西，实验坑也很多，很容易因为找不到教程或者环境原因浪费2-3天，所以大家做lab需要积极需找教程。 project 主要是环境问题，做起来大概需要2-3天，和 wk 班的 project 相比会简单很多。 lab 和 project 的坑虽然很多，但是验收标准比较低，差不多就可以过。 复习主要看 PPT 和历年卷就可以了，基
全角点号后面不要加空格

2023-07-11 11:36 UTC, TonyCrane commented
我基本修好了，除了那个 “lab 虽然也有 -10%” 没看懂

2023-07-11 11:37 UTC, TonyCrane commented
草 又加了一个操作系统

一个 PR 里面不要有太多无关的部分好不好 https://github.com/ZJU-Turing/TuringCourses/pull/80#issuecomment-1628411832

2023-07-11 11:38 UTC, TonyCrane commented on docs/major_mandatory/computer_architecture/index.md
> +体系结构的任务还是比较轻的，课程内容虽然设计的量比较大，包括cache、分支预测、SIMD、多发射、乱序、多核等一系列内容，但是都不是非常深入，大多数重在了解，其中乱序的算法、内存一致性协议达到了定量的程度，其他主要还是定性的程度。lab比计组的简单很多，不同于计组的纯手搓，体系的lab都给了代码，只需要做适当的填空即可，很多时候一个下午就可以了，甚至lab1、lab3、lab4其实计组很多人都
哦 是 lab 第一次验收不通过扣 10% 的规则？写明白点吧

2023-07-11 12:14 UTC, TonyCrane requested changes

2023-07-11 12:14 UTC, TonyCrane commented on docs/major_basic/operating_system/index.md
> +</div>
这里不用带课程名，以及 AI 也是专业基础

2023-07-11 12:14 UTC, TonyCrane commented on docs/major_basic/operating_system/index.md
> +* 其他还有qume的使用、交叉编译、内核模块编译、elf文件格式、C代码bin布局等内容
qemu，ELF 建议大写

2023-07-11 12:14 UTC, TonyCrane commented on docs/major_basic/operating_system/index.md
> +* 迟交一天扣10%直到0分为止
缩进，最后一项应该不属于列表内容

2023-07-11 12:14 UTC, TonyCrane commented on docs/major_basic/operating_system/index.md
> +PPT的内容基本是齐全的，不过涉及到linux代码的内容还是要参考PPT和课堂讲解
一样，不要多加空格，加个换行，行尾加个句号

2023-07-11 12:14 UTC, TonyCrane commented on docs/major_basic/operating_system/index.md
> +  * 期末考试
这是否写了跟没写一样（

而且前面写的是七个 lab（

缩进四空格

2023-07-11 12:28 UTC, TonyCrane commented
OS 的分数占比有更具体的吗，没有的话就先这样了

2023-07-11 12:41 UTC, ZhouTimeMachine commented
OS 一共 7 个 Lab，分为 Lab0 - Lab6，Lab0 为实验环境搭建，但是工作量也不小，而且也需要写实验报告。
每个 Lab 具体占分比例没有公布，但是 Lab6 中的 fork 在期末被分离出来作为 5% 的平时分 bonus。
Lab 的 delay penalty 为每迟一天 -10%。
总体的分数比例为 Lab (50%) + Final Exam (50%)。

2023-07-14 08:31 UTC, TonyCrane commented
> OS 一共 7 个 Lab，分为 Lab0 - Lab6，Lab0 为实验环境搭建，但是工作量也不小，而且也需要写实验报告。 每个 Lab 具体占分比例没有公布，但是 Lab6 中的 fork 在期末被分离出来作为 5% 的平时分 bonus。 Lab 的 delay penalty 为每迟一天 -10%。 总体的分数比例为 Lab (50%) + Final Exam (50%)。

等着加进去

2023-07-14 08:58 UTC, merged